[tool.poetry]
name = "mlflow-docker"
version = "1.0.0"
description = "MLFlow wiht OIDC docker image"
authors = ["Alexander Kharkevich <alex@kharkevich.org>"]

[tool.poetry.dependencies]
python = "^3.12"
# mlflow = { version = "^2.16.2", extras = ["extras", "pipelines"] }
mlflow-oidc-auth = "^2.0.2"
mlflow-skinny = "2.17.0"

# PostgreSQL support
psycopg = "^3.2.3"

# AWS S3 Artifact Store support
boto3 = "^1.35.35"

# Azure Blob Storage Artifact Store support
azure-storage-blob = "^12.23.1"
azure-identity = "^1.18.0"

# Google Cloud Storage Artifact Store support
google-cloud-storage = "^2.18.2"

# SFTP Artifact Store support
pysftp = "^0.2.9"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
